spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000


eureka:
  instance:
    prefer-ip-address: true  # 强制使用 IP 注册，而不是主机名
